spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/pharmacy?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.bozhonghulian.pojo

